# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f50a53549c9ae3193ba9132d6b309e6bcab3da989430e9eea24be763456ed355da6d1a1202254b61291c4946867106f64d30fbff684001443a7f94ff8b593af

test:
  secret_key_base: 35a4f2f99f91923f465d704a67edee1e1b1e8b29c1511f758ae33fd6179775a5c99a648a752416bc56eac45575a61015b24ae5ab0cda212a7de6ce0871983242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
